# ЛР 5
## Задания:
1. Провести классификацию найденного датасета, методами решающего дерева и случайного леса . В формате Markdown написать пояснения. Объяснить почему были выбраны именно такие гиперпараметры, была ли перекрестная проверка, и т.д.

## Описание датасета:
Датасет удовлетворённости пассажиров их полётом на самолёте.
### Данные:
* id - id пассажира
* <b>Satisfaction_v2 (целевой столбец) - удовлетворённость полётом (satisfied/neutral or dissatisfaction)</b>
* Gender - пол пассажира
* Customer Type - лояльность пассажира (Loyal customer, disloyal customer)
* Age - возраст пассажира на момент полёта
* Type of Travel - цель полёта (Personal Travel/Business Travel)
* Class - класс полёта (Business, Eco, Eco Plus)
* Flight distance - дальность полёта
* Seat comfort - удовлетворённость удобством сидения (0-5)
* Departure/Arrival time convenient - удовлетворённость удобством времени отправления/прибытия (0-5)
* Food and drink - удовлетворённсть едой и напитками (0-5)
* Gate location - удовлетворённость удобством размещения гейтов (0-5)
* Inflight wifi service - наличие и качество WiFi на борту (0 - WiFi отсутствует, 1-5)
* Inflight entertainment - удовлетворённость развлечениям в полёте (0-5)
* Online support - удовлетворённость онлайн поддержкой (0-5)
* Ease of Online booking - удовлетворённость простотой бронирования билетов онлайн (0-5)
* On-board service - удовлетворённость обслуживанием в полёте (0-5)
* Leg room service - удовлетворённость расстоянием между ногами и сидением (0-5)
* Baggage handling - удовлетворённость работы с багажом (0-5)
* Checkin service - удовлетворённость обслуживанием при регистрации (0-5)
* Cleanliness - удовлетворённость чистотой на борту (0-5)
* Online boarding - удовлетворённость простотой получения онлайн талона на посадку (0-5)
* Departure Delay in Minutes - задержка отправления рейса
* Arrival Delay in Minutes - задержка прибытия рейса

In [2]:
import pandas as pd
import numpy as np

df = pd.read_excel('satisfaction.xlsx', index_col=0)

In [3]:
df

,satisfaction_v2,Gender,Customer Type,Age,Type of Travel,Class,Flight Distance,Seat comfort,Departure/Arrival time convenient,Food and drink,...,Online support,Ease of Online booking,On-board service,Leg room service,Baggage handling,Checkin service,Cleanliness,Online boarding,Departure Delay in Minutes,Arrival Delay in Minutes
id,,,,,,,,,,,,,,,,,,,,,
11112,satisfied,Female,Loyal Customer,65,Personal Travel,Eco,265,0,0,0,...,2,3,3,0,3,5,3,2,0,0.0
110278,satisfied,Male,Loyal Customer,47,Personal Travel,Business,2464,0,0,0,...,2,3,4,4,4,2,3,2,310,305.0
103199,satisfied,Female,Loyal Customer,15,Personal Travel,Eco,2138,0,0,0,...,2,2,3,3,4,4,4,2,0,0.0
47462,satisfied,Female,Loyal Customer,60,Personal Travel,Eco,623,0,0,0,...,3,1,1,0,1,4,1,3,0,0.0
120011,satisfied,Female,Loyal Customer,70,Personal Travel,Eco,354,0,0,0,...,4,2,2,0,2,4,2,5,0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
119211,satisfied,Female,disloyal Customer,29,Personal Travel,Eco,1731,5,5,5,...,2,2,3,3,4,4,4,2,0,0.0
97768,neutral or dissatisfied,Male,disloyal Customer,63,Personal Travel,Business,2087,2,3,2,...,1,3,2,3,3,1,2,1,174,172.0
125368,neutral or dissatisfied,Male,disloyal Customer,69,Personal Travel,Eco,2320,3,0,3,...,2,4,4,3,4,2,3,2,155,163.0
251,neutral or dissatisfied,Male,disloyal Customer,66,Personal Travel,Eco,2450,3,2,3,...,2,3,3,2,3,2,1,2,193,205.0
84566,neutral or dissatisfied,Female,disloyal Customer,38,Personal Travel,Eco,4307,3,4,3,...,3,4,5,5,5,3,3,3,185,186.0

Замена текстовых категориальных признаков на числовые

In [4]:
from sklearn.preprocessing import LabelEncoder
labelencoder = LabelEncoder()
df['satisfaction_v2'] = labelencoder.fit_transform(df['satisfaction_v2'])
df['Gender'] =  labelencoder.fit_transform(df['Gender'])
df['Customer Type'] =  labelencoder.fit_transform(df['Customer Type'])
df['Type of Travel'] = labelencoder.fit_transform(df['Type of Travel'])
df['Class'] =  labelencoder.fit_transform(df['Class'])
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 129880 entries, 11112 to 84566
Data columns (total 23 columns):
 #   Column                             Non-Null Count   Dtype
---  ------                             --------------   -----
 0   satisfaction_v2                    129880 non-null  int32
 1   Gender                             129880 non-null  int32
 2   Customer Type                      129880 non-null  int32
 3   Age                                129880 non-null  int64
 4   Type of Travel                     129880 non-null  int32
 5   Class                              129880 non-null  int32
 6   Flight Distance                    129880 non-null  int64
 7   Seat comfort                       129880 non-null  int64
 8   Departure/Arrival time convenient  129880 non-null  int64
 9   Food and drink                     129880 non-null  int64
 10  Gate location                      129880 non-null  int64
 11  Inflight wifi service              129880 non-null  int64
 12  Inflight entertainment             129880 non-null  int64
 13  Online support                     129880 non-null  int64
 14  Ease of Online booking             129880 non-null  int64
 15  On-board service                   129880 non-null  int64
 16  Leg room service                   129880 non-null  int64
 17  Baggage handling                   129880 non-null  int64
 18  Checkin service                    129880 non-null  int64
 19  Cleanliness                        129880 non-null  int64
 20  Online boarding                    129880 non-null  int64
 21  Departure Delay in Minutes         129880 non-null  int64
 22  Arrival Delay in Minutes           129487 non-null  float64
dtypes: float64(1), int32(5), int64(17)
memory usage: 21.3 MB

Замена отсутствующих значений задержки прибытия нулями

In [5]:
df['Arrival Delay in Minutes'] = df['Arrival Delay in Minutes'].fillna(0)
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 129880 entries, 11112 to 84566
Data columns (total 23 columns):
 #   Column                             Non-Null Count   Dtype
---  ------                             --------------   -----
 0   satisfaction_v2                    129880 non-null  int32
 1   Gender                             129880 non-null  int32
 2   Customer Type                      129880 non-null  int32
 3   Age                                129880 non-null  int64
 4   Type of Travel                     129880 non-null  int32
 5   Class                              129880 non-null  int32
 6   Flight Distance                    129880 non-null  int64
 7   Seat comfort                       129880 non-null  int64
 8   Departure/Arrival time convenient  129880 non-null  int64
 9   Food and drink                     129880 non-null  int64
 10  Gate location                      129880 non-null  int64
 11  Inflight wifi service              129880 non-null  int64
 12  Inflight entertainment             129880 non-null  int64
 13  Online support                     129880 non-null  int64
 14  Ease of Online booking             129880 non-null  int64
 15  On-board service                   129880 non-null  int64
 16  Leg room service                   129880 non-null  int64
 17  Baggage handling                   129880 non-null  int64
 18  Checkin service                    129880 non-null  int64
 19  Cleanliness                        129880 non-null  int64
 20  Online boarding                    129880 non-null  int64
 21  Departure Delay in Minutes         129880 non-null  int64
 22  Arrival Delay in Minutes           129880 non-null  float64
dtypes: float64(1), int32(5), int64(17)
memory usage: 21.3 MB

Разбиение на train/test и обучение модели с разными параметрами (Решающее дерево)

In [7]:
from sklearn.model_selection import train_test_split
from sklearn.model_selection import GridSearchCV
from imblearn.under_sampling import RandomUnderSampler
from sklearn.tree import DecisionTreeClassifier
import matplotlib.pyplot as plt


X = df.drop(columns=['satisfaction_v2'])
Y = df['satisfaction_v2']
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.3, random_state=27)


under_sampler = RandomUnderSampler(random_state=27)
X_resampled, Y_resampled = under_sampler.fit_resample(X_train, Y_train)

decision_tree = DecisionTreeClassifier()
dt_params = {
    'max_depth': [None, 5, 10, 15, 20],
    'min_samples_split': [2, 5, 10],
    'min_samples_leaf': [1, 2, 4]
}

dt_grid_search = GridSearchCV(decision_tree, dt_params, cv=5)
dt_grid_search.fit(X_resampled, Y_resampled)

dt_best_params = dt_grid_search.best_params_
dt_best_max_depth = dt_best_params['max_depth']
dt_best_min_ss = dt_best_params['min_samples_split']
dt_best_min_sl = dt_best_params['min_samples_leaf']

print(f"Лучшие параметры для решающего дерева: Max Depth: {dt_best_max_depth}, Min samples split: {dt_best_min_ss}, Min samples leaf: {dt_best_min_sl}")

Лучшие параметры для решающего дерева: Max Depth: 15, Min samples split: 10, Min samples leaf: 2

Оценка точности и отчёт:

In [14]:
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report

decision_tree_model = DecisionTreeClassifier(max_depth = dt_best_max_depth, min_samples_leaf =  dt_best_min_sl, min_samples_split = dt_best_min_ss)
decision_tree_model.fit(X_resampled, Y_resampled)

Y_pred = decision_tree_model.predict(X_test)

accuracy = accuracy_score(Y_test, Y_pred)
print(f"Точность модели: {accuracy}")

report = classification_report(Y_test, Y_pred, zero_division=1)
print(report)

Точность модели: 0.9421004003695719
              precision    recall  f1-score   support

           0       0.92      0.95      0.94     17571
           1       0.96      0.93      0.95     21393

    accuracy                           0.94     38964
   macro avg       0.94      0.94      0.94     38964
weighted avg       0.94      0.94      0.94     38964

Разбиение на train/test и обучение модели с разными параметрами (Случайный лес)

In [12]:
from sklearn.ensemble import RandomForestClassifier

X = df.drop(columns=['satisfaction_v2'])
Y = df['satisfaction_v2']
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.3, random_state=27)


under_sampler = RandomUnderSampler(random_state=27)
X_resampled, Y_resampled = under_sampler.fit_resample(X_train, Y_train)

random_forest = RandomForestClassifier()
rf_params = {
    'n_estimators': [50, 100, 150, 200],
    'max_depth': [None, 5, 10, 15, 20],
    'min_samples_split': [2, 5, 10],
    'min_samples_leaf': [1, 2, 4]
}

rf_grid_search = GridSearchCV(random_forest, rf_params, cv=5)
rf_grid_search.fit(X_resampled, Y_resampled)

rf_best_params = rf_grid_search.best_params_
rf_best_n_estimators = rf_best_params['n_estimators']
rf_best_max_depth = rf_best_params['max_depth']
rf_best_min_ss = rf_best_params['min_samples_split']
rf_best_min_sl = rf_best_params['min_samples_leaf']

print(f"Лучшие параметры для случайного леса: N estimators: {rf_best_n_estimators}, Max Depth: {dt_best_max_depth}, Min samples split: {dt_best_min_ss}, Min samples leaf: {dt_best_min_sl}")

Лучшие параметры для случайного леса: N estimators: 200, Max Depth: 15, Min samples split: 10, Min samples leaf: 2

Оценка точности и отчёт:

In [15]:
random_forest_model = RandomForestClassifier(n_estimators = rf_best_n_estimators, max_depth = rf_best_max_depth, min_samples_leaf =  rf_best_min_sl, min_samples_split = rf_best_min_ss)
random_forest_model.fit(X_resampled, Y_resampled)

Y_pred = random_forest_model.predict(X_test)

accuracy = accuracy_score(Y_test, Y_pred)
print(f"Точность модели: {accuracy}")

report = classification_report(Y_test, Y_pred, zero_division=1)
print(report)

Точность модели: 0.9579868596653321
              precision    recall  f1-score   support

           0       0.94      0.97      0.95     17571
           1       0.97      0.95      0.96     21393

    accuracy                           0.96     38964
   macro avg       0.96      0.96      0.96     38964
weighted avg       0.96      0.96      0.96     38964